// backend/src/services/eventService.ts
import EventEmitter from "events";

class EventService extends EventEmitter {
  constructor() {
    super();
    // Increase max listeners to avoid warnings
    this.setMaxListeners(50);
  }

  // ==================== BILLING EVENTS ====================

  emitBillingCreated(data: {
    billing: any;
    applicationId?: string;
    type?: "monthly" | "pro-rated" | "installation";
    customerName?: string;
    autoGenerated?: boolean;
    manuallyGenerated?: boolean;
    recovered?: boolean;
    isBackdated?: boolean;
    monthOffset?: number;
  }) {
    this.emit("billing:created", data);
    this.emit("dashboard:update", { ...data, event: "billing:created" });
  }

  emitBillingPaid(data: {
    billId: string;
    invoiceNumber: string;
    applicationId?: string;
    paymentId: string;
    amount: number;
    isInstallation?: boolean;
    isProRated?: boolean;
    customerName?: string;
  }) {
    this.emit("billing:paid", data);
    this.emit("dashboard:update", { ...data, event: "billing:paid" });
  }

  emitBillingUpdated(data: {
    applicationId?: string;
    type?: string;
    count?: number;
    customerName?: string;
    billId?: string;
  }) {
    this.emit("billing:updated", data);
    this.emit("dashboard:update", { ...data, event: "billing:updated" });
  }

  emitBillingDeleted(data: {
    billId?: string;
    applicationId?: string;
    reason?: string;
    customerName?: string;
  }) {
    this.emit("billing:deleted", data);
    this.emit("dashboard:update", { ...data, event: "billing:deleted" });
  }

  // ==================== BILLING CYCLE EVENTS ====================

  emitBillingCycleCreated(data: {
    billingCycle: any;
    applicationId?: string;
    customerName?: string;
    isBackdated?: boolean;
  }) {
    this.emit("billingCycle:created", data);
    this.emit("dashboard:update", { ...data, event: "billingCycle:created" });
  }

  emitBillingCycleUpdated(data: {
    billingCycleId: string;
    applicationId?: string;
    status?: string;
    reason?: string;
    customerName?: string;
  }) {
    this.emit("billingCycle:updated", data);
    this.emit("dashboard:update", { ...data, event: "billingCycle:updated" });
  }

  emitBillingCycleDeleted(data: {
    billingCycleId: string;
    applicationId?: string;
    reason?: string;
    customerName?: string;
  }) {
    this.emit("billingCycle:deleted", data);
    this.emit("dashboard:update", { ...data, event: "billingCycle:deleted" });
  }

  // ==================== CUSTOMER EVENTS ====================

  emitCustomerCreated(data: {
    customers?: any[];
    count?: number;
    type?: string;
    applicationId?: string;
    customerName?: string;
  }) {
    this.emit("customer:created", data);
    this.emit("dashboard:update", { ...data, event: "customer:created" });
  }

  emitCustomerUpdated(data: {
    applicationId?: string;
    customerName?: string;
    status?: string;
    type?: string;
  }) {
    this.emit("customer:updated", data);
    this.emit("dashboard:update", { ...data, event: "customer:updated" });
  }

  // ==================== PAYMENT EVENTS ====================

  emitPaymentCreated(data: {
    paymentId: string;
    billingId: string;
    applicationId?: string;
    amount: number;
    type?: string;
  }) {
    this.emit("payment:created", data);
    this.emit("dashboard:update", { ...data, event: "payment:created" });
  }

  emitPaymentConfirmed(data: {
    payment: any;
    billingId: string;
    applicationId?: string;
    type?: string;
  }) {
    this.emit("payment:confirmed", data);
    this.emit("dashboard:update", { ...data, event: "payment:confirmed" });
  }

  // ==================== SETTINGS EVENTS ====================

  emitSettingsUpdated(data: { settings: any; updatedBy?: string }) {
    this.emit("settings:updated", data);
    this.emit("dashboard:update", { ...data, event: "settings:updated" });
  }

  // ==================== SUSPENSION EVENTS ====================

  emitSuspensionUpdated(data: {
    count: number;
    type: string;
    timestamp: Date;
  }) {
    this.emit("suspension:updated", data);
    this.emit("dashboard:update", { ...data, event: "suspension:updated" });
  }

  // ==================== DASHBOARD UPDATE EVENTS ====================

  emitDashboardUpdate(data: {
    reason: string;
    applicationId?: string;
    customerName?: string;
    billId?: string;
    billingCycleId?: string;
    count?: number;
    month?: string;
    billsCount?: number;
    [key: string]: any;
  }) {
    this.emit("dashboard:update", data);
  }

  // ==================== BILLS GENERATED EVENTS ====================

  emitBillsGenerated(data: {
    count: number;
    month?: string;
    dueDate?: string;
    autoGenerated?: boolean;
  }) {
    this.emit("bills:generated", data);
    this.emit("dashboard:update", { ...data, event: "bills:generated" });
  }

  // ==================== NEW CUSTOMER DETECTED EVENTS ====================

  emitNewCustomerDetected(data: {
    customer: any;
    applicationId: string;
    customerName: string;
  }) {
    this.emit("new_customer:detected", data);
    this.emit("dashboard:update", { ...data, event: "new_customer:detected" });
  }

  // ==================== BILLS RECOVERED EVENTS ====================

  emitBillsRecovered(data: {
    applicationId: string;
    customerName: string;
    count: number;
  }) {
    this.emit("bills:recovered", data);
    this.emit("dashboard:update", { ...data, event: "bills:recovered" });
  }

  // ==================== PAYMENT SUBMITTED EVENTS ====================

  emitPaymentSubmitted(data: {
    paymentId: string;
    billingId: string;
    applicationId?: string;
    amount: number;
    type?: string;
  }) {
    this.emit("payment:submitted", data);
    this.emit("dashboard:update", { ...data, event: "payment:submitted" });
  }
}

export const eventService = new EventService();
export default eventService;
